version: "3.9"

services:
  minstroy_postgres:
    image: postgres
    restart: always
    container_name: minstroy_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: parser
    ports:
      - "5432:5432"
    volumes:
      - ./var/lib/postgresql/data:/var/lib/postgresql/data

  minstroy_api:
    image: python:3.12.2-bullseye
    container_name: minstroy_api
    restart: always
    working_dir: /api
    volumes:
      - ./:/api
    ports:
      - "8000:8000"
    command: bash -c "
      pip install -r requirements.txt ;
      alembic init alembic ;
      cp env.py ./alembic ;
      alembic revision --autogenerate -m 'init' ;
      alembic upgrade head ;
      uvicorn api:app --host 0.0.0.0 --port 8000"

